In [1]:
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "cfbd.settings")
import django
django.setup()

#from collections import defaultdict
import random

import pandas as pd

from main import models

In [2]:
SEASON = 2020

In [3]:
master = pd.read_csv("masterSchedule{}.csv".format(SEASON), index_col=0)
master

,AF,AKR,APP,ARK,ARMY,ARST,ASU,AUB,BALL,BAMA,...,VT,WAKE,WASH,WISC,WKU,WMU,WSU,WVU,WYO,ZONA
AF,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
AKR,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
APP,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ARK,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
ARMY,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WMU,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
WSU,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,1
WVU,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
WYO,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ZONA,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0

## Error Checking

In [4]:
for c in master.columns:
    if master[c].sum() != 9:
        print(c, master[c].sum())

ARMY 0
BYU 0
LIB 0
ND 0

In [5]:
for r in master.index:
    if master.loc[r].sum() != 9:
        print(r, master.loc[r].sum())

ARMY 0
BYU 0
LIB 0
ND 0

## Initialize Weekly Matrix

In [7]:
weekly = pd.DataFrame([["" for i in range(1, 15+1)] for j in range(128)], columns=range(1, 15+1))
weekly.index = master.index
weekly

     1  2  3  4  5  6  7  8  9  10 11 12 13 14 15
AF
AKR
APP
ARK
ARMY
...  .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
WMU
WSU
WVU
WYO
ZONA

[128 rows x 15 columns]

## Weekly Schedule

In [8]:
for i, r in weekly.iterrows():
    print(i)
    #print(r)
    s = models.School.objects.get(abbreviation=i)
    opponents = master.loc[master[i]==1,i].keys()
    print(opponents)
    
    for abb in opponents:
        
        #print(abb)
        if abb not in r.values and "@" + abb not in r.values:
            o = models.School.objects.get(abbreviation=abb)
            
            if o.conference != s.conference:  # noncon
                week = random.randint(1, 5)
                tries = 0
                while r[week] != "" or weekly.at[abb, week] != "":
                    week = random.randint(1, 5)
                    tries += 1
                    
                    if tries >= 100:
                        break
                
                if tries < 100:
                    weekly.at[i, week] = abb
                    weekly.at[abb, week] = i
                    #print(week)

                    # H/A
                    if random.randint(0,1):
                        weekly.at[i, week] = "@" + abb
                    else:
                        weekly.at[abb, week] = "@" + i
                else:
                    print("SCHEDULING ERROR:", abb)
            
            else:  # conference
                week = random.randint(4, 15)
                tries = 0
                while r[week] != "" or weekly.at[abb, week] != "":
                    week = random.randint(4, 15)
                    tries += 1
                    
                    if tries >= 100:
                        break
                
                if tries < 100:
                    weekly.at[i, week] = abb
                    weekly.at[abb, week] = i
                    #print(week)

                    # H/A
                    if random.randint(0,1):
                        weekly.at[i, week] = "@" + abb
                    else:
                        weekly.at[abb, week] = "@" + i
                else:
                    print("SCHEDULING ERROR:", abb)  # to fix manually
        else:
            pass
            #print("already scheduled")

    #print(weekly.loc[i])
    print()
    #break

AF
Index(['BSU', 'CSU', 'NEV', 'SDSU', 'SJSU', 'UNLV', 'UNM', 'USU', 'WYO'], dtype='object')

AKR
Index(['BALL', 'BGSU', 'BUFF', 'CMU', 'EMU', 'KNTS', 'MIOH', 'OHIO', 'WMU'], dtype='object')

APP
Index(['ARST', 'CCAR', 'GAST', 'GSOU', 'TROY', 'TXST', 'ULL', 'ULM', 'USA'], dtype='object')

ARK
Index(['AUB', 'BAMA', 'LSU', 'MISS', 'MIZZ', 'MSST', 'SCAR', 'TAMU', 'TENN'], dtype='object')

ARMY
Index([], dtype='object')

ARST
Index(['APP', 'CCAR', 'GAST', 'GSOU', 'TROY', 'TXST', 'ULL', 'ULM', 'USA'], dtype='object')

ASU
Index(['COL', 'ORST', 'STAN', 'UCLA', 'USC', 'UTAH', 'WASH', 'WSU', 'ZONA'], dtype='object')

AUB
Index(['ARK', 'BAMA', 'KENT', 'LSU', 'MISS', 'MSST', 'SCAR', 'TAMU', 'UGA'], dtype='object')

BALL
Index(['AKR', 'BGSU', 'BUFF', 'CMU', 'EMU', 'NIU', 'OHIO', 'TOL', 'WMU'], dtype='object')

BAMA
Index(['ARK', 'AUB', 'FLA', 'LSU', 'MISS', 'MSST', 'TAMU', 'TENN', 'VAND'], dtype='object')

BAY
Index(['ISU', 'KAN', 'KSU', 'OKLA', 'OKST', 'TCU', 'TEX', 'TTU', 'WVU'], dtype='object')

BC
Index(['CLEM', 'CUSE', 'DUKE', 'FSU', 'GT', 'LOU', 'NCST', 'VT', 'WAKE'], dtype='object')

BGSU
Index(['AKR', 'BALL', 'BUFF', 'CMU', 'EMU', 'KNTS', 'MIOH', 'OHIO', 'WMU'], dtype='object')

BSU
Index(['AF', 'CSU', 'FRES', 'HWI', 'NEV', 'UNLV', 'UNM', 'USU', 'WYO'], dtype='object')

BUFF
Index(['AKR', 'BALL', 'BGSU', 'KNTS', 'MIOH', 'NIU', 'OHIO', 'TOL', 'WMU'], dtype='object')

BYU
Index([], dtype='object')

CAL
Index(['COL', 'ORE', 'ORST', 'STAN', 'UCLA', 'USC', 'UTAH', 'WASH', 'WSU'], dtype='object')

CCAR
Index(['APP', 'ARST', 'GAST', 'GSOU', 'TROY', 'TXST', 'ULL', 'ULM', 'USA'], dtype='object')

CHAR
Index(['FAU', 'FIU', 'MRSH', 'MTSU', 'ODU', 'UAB', 'UTEP', 'UTSA', 'WKU'], dtype='object')

CIN
Index(['CONN', 'ECU', 'HOU', 'MEM', 'NAVY', 'TEM', 'TULN', 'UCF', 'USF'], dtype='object')

CLEM
Index(['BC', 'CUSE', 'FSU', 'GT', 'LOU', 'NCST', 'PITT', 'UNC', 'WAKE'], dtype='object')

CMU
Index(['AKR', 'BALL', 'BGSU', 'EMU', 'KNTS', 'MIOH', 'NIU', 'TOL', 'WMU'], dtype='object')

COL
Index(['ASU', 'CAL', 'ORE', 'ORST', 'UCLA', 'USC', 'UTAH', 'WSU', 'ZONA'], dtype='object')

CONN
Index(['CIN', 'ECU', 'HOU', 'SMU', 'TEM', 'TULN', 'TULS', 'UCF', 'USF'], dtype='object')

CSU
Index(['AF', 'BSU', 'FRES', 'HWI', 'NEV', 'SJSU', 'UNM', 'USU', 'WYO'], dtype='object')

CUSE
Index(['BC', 'CLEM', 'FSU', 'LOU', 'MIA', 'NCST', 'PITT', 'VT', 'WAKE'], dtype='object')

DUKE
Index(['BC', 'GT', 'LOU', 'MIA', 'PITT', 'UNC', 'UVA', 'VT', 'WAKE'], dtype='object')

ECU
Index(['CIN', 'CONN', 'MEM', 'NAVY', 'SMU', 'TEM', 'TULN', 'UCF', 'USF'], dtype='object')

EMU
Index(['AKR', 'BALL', 'BGSU', 'CMU', 'KNTS', 'MIOH', 'NIU', 'TOL', 'WMU'], dtype='object')

FAU
Index(['CHAR', 'FIU', 'LT', 'MRSH', 'MTSU', 'ODU', 'UAB', 'UTSA', 'WKU'], dtype='object')

FIU
Index(['CHAR', 'FAU', 'MRSH', 'MTSU', 'ODU', 'UNT', 'USM', 'UTEP', 'WKU'], dtype='object')

FLA
Index(['BAMA', 'KENT', 'LSU', 'MISS', 'MIZZ', 'SCAR', 'TENN', 'UGA', 'VAND'], dtype='object')

FRES
Index(['BSU', 'CSU', 'HWI', 'NEV', 'SDSU', 'SJSU', 'UNLV', 'UNM', 'USU'], dtype='object')

FSU
Index(['BC', 'CLEM', 'CUSE', 'LOU', 'MIA', 'NCST', 'PITT', 'UNC', 'WAKE'], dtype='object')

GAST
Index(['APP', 'ARST', 'CCAR', 'GSOU', 'TROY', 'TXST', 'ULL', 'ULM', 'USA'], dtype='object')

GSOU
Index(['APP', 'ARST', 'CCAR', 'GAST', 'TROY', 'TXST', 'ULL', 'ULM', 'USA'], dtype='object')

GT
Index(['BC', 'CLEM', 'DUKE', 'MIA', 'NCST', 'PITT', 'UNC', 'UVA', 'VT'], dtype='object')

HOU
Index(['CIN', 'CONN', 'MEM', 'NAVY', 'SMU', 'TULN', 'TULS', 'UCF', 'USF'], dtype='object')

HWI
Index(['BSU', 'CSU', 'FRES', 'NEV', 'SDSU', 'SJSU', 'UNLV', 'UNM', 'WYO'], dtype='object')

ILL
Index(['IOWA', 'MARY', 'MINN', 'MSU', 'NEB', 'NW', 'PSU', 'PURD', 'WISC'], dtype='object')

IND
Index(['IOWA', 'MARY', 'MICH', 'MSU', 'NEB', 'OHST', 'PSU', 'PURD', 'RUTG'], dtype='object')

IOWA
Index(['ILL', 'IND', 'MICH', 'MINN', 'NEB', 'NW', 'OHST', 'PURD', 'WISC'], dtype='object')

ISU
Index(['BAY', 'KAN', 'KSU', 'OKLA', 'OKST', 'TCU', 'TEX', 'TTU', 'WVU'], dtype='object')

KAN
Index(['BAY', 'ISU', 'KSU', 'OKLA', 'OKST', 'TCU', 'TEX', 'TTU', 'WVU'], dtype='object')

KENT
Index(['AUB', 'FLA', 'MIZZ', 'MSST', 'SCAR', 'TAMU', 'TENN', 'UGA', 'VAND'], dtype='object')

KNTS
Index(['AKR', 'BGSU', 'BUFF', 'CMU', 'EMU', 'MIOH', 'NIU', 'OHIO', 'TOL'], dtype='object')

KSU
Index(['BAY', 'ISU', 'KAN', 'OKLA', 'OKST', 'TCU', 'TEX', 'TTU', 'WVU'], dtype='object')

LIB
Index([], dtype='object')

LOU
Index(['BC', 'CLEM', 'CUSE', 'DUKE', 'FSU', 'NCST', 'UVA', 'VT', 'WAKE'], dtype='object')

LSU
Index(['ARK', 'AUB', 'BAMA', 'FLA', 'MISS', 'MIZZ', 'MSST', 'TAMU', 'UGA'], dtype='object')

LT
Index(['FAU', 'MRSH', 'RICE', 'UAB', 'UNT', 'USM', 'UTEP', 'UTSA', 'WKU'], dtype='object')

MARY
Index(['ILL', 'IND', 'MICH', 'MINN', 'MSU', 'OHST', 'PSU', 'PURD', 'RUTG'], dtype='object')

MEM
Index(['CIN', 'ECU', 'HOU', 'NAVY', 'SMU', 'TEM', 'TULN', 'TULS', 'USF'], dtype='object')

MIA
Index(['CUSE', 'DUKE', 'FSU', 'GT', 'PITT', 'UNC', 'UVA', 'VT', 'WAKE'], dtype='object')

MICH
Index(['IND', 'IOWA', 'MARY', 'MSU', 'NEB', 'OHST', 'PSU', 'PURD', 'RUTG'], dtype='object')

MINN
Index(['ILL', 'IOWA', 'MARY', 'NEB', 'NW', 'OHST', 'PURD', 'RUTG', 'WISC'], dtype='object')

MIOH
Index(['AKR', 'BGSU', 'BUFF', 'CMU', 'EMU', 'KNTS', 'NIU', 'OHIO', 'TOL'], dtype='object')

MISS
Index(['ARK', 'AUB', 'BAMA', 'FLA', 'LSU', 'MIZZ', 'MSST', 'TAMU', 'VAND'], dtype='object')

MIZZ
Index(['ARK', 'FLA', 'KENT', 'LSU', 'MISS', 'SCAR', 'TENN', 'UGA', 'VAND'], dtype='object')

MRSH
Index(['CHAR', 'FAU', 'FIU', 'LT', 'MTSU', 'ODU', 'RICE', 'UTSA', 'WKU'], dtype='object')

MSST
Index(['ARK', 'AUB', 'BAMA', 'KENT', 'LSU', 'MISS', 'TAMU', 'TENN', 'UGA'], dtype='object')
SCHEDULING ERROR: UGA

MSU
Index(['ILL', 'IND', 'MARY', 'MICH', 'NW', 'OHST', 'PSU', 'RUTG', 'WISC'], dtype='object')

MTSU
Index(['CHAR', 'FAU', 'FIU', 'MRSH', 'ODU', 'RICE', 'UNT', 'USM', 'WKU'], dtype='object')

NAVY
Index(['CIN', 'ECU', 'HOU', 'MEM', 'SMU', 'TEM', 'TULN', 'TULS', 'UCF'], dtype='object')

NCST
Index(['BC', 'CLEM', 'CUSE', 'FSU', 'GT', 'LOU', 'UNC', 'UVA', 'WAKE'], dtype='object')

ND
Index([], dtype='object')

NEB
Index(['ILL', 'IND', 'IOWA', 'MICH', 'MINN', 'NW', 'PSU', 'PURD', 'WISC'], dtype='object')

NEV
Index(['AF', 'BSU', 'CSU', 'FRES', 'HWI', 'SDSU', 'SJSU', 'UNLV', 'WYO'], dtype='object')

NIU
Index(['BALL', 'BUFF', 'CMU', 'EMU', 'KNTS', 'MIOH', 'OHIO', 'TOL', 'WMU'], dtype='object')

NW
Index(['ILL', 'IOWA', 'MINN', 'MSU', 'NEB', 'OHST', 'PURD', 'RUTG', 'WISC'], dtype='object')

ODU
Index(['CHAR', 'FAU', 'FIU', 'MRSH', 'MTSU', 'UAB', 'UNT', 'USM', 'WKU'], dtype='object')

OHIO
Index(['AKR', 'BALL', 'BGSU', 'BUFF', 'KNTS', 'MIOH', 'NIU', 'TOL', 'WMU'], dtype='object')

OHST
Index(['IND', 'IOWA', 'MARY', 'MICH', 'MINN', 'MSU', 'NW', 'PSU', 'RUTG'], dtype='object')

OKLA
Index(['BAY', 'ISU', 'KAN', 'KSU', 'OKST', 'TCU', 'TEX', 'TTU', 'WVU'], dtype='object')

OKST
Index(['BAY', 'ISU', 'KAN', 'KSU', 'OKLA', 'TCU', 'TEX', 'TTU', 'WVU'], dtype='object')

ORE
Index(['CAL', 'COL', 'ORST', 'STAN', 'UCLA', 'UTAH', 'WASH', 'WSU', 'ZONA'], dtype='object')

ORST
Index(['ASU', 'CAL', 'COL', 'ORE', 'STAN', 'USC', 'UTAH', 'WASH', 'WSU'], dtype='object')

PITT
Index(['CLEM', 'CUSE', 'DUKE', 'FSU', 'GT', 'MIA', 'UNC', 'UVA', 'VT'], dtype='object')

PSU
Index(['ILL', 'IND', 'MARY', 'MICH', 'MSU', 'NEB', 'OHST', 'RUTG', 'WISC'], dtype='object')

PURD
Index(['ILL', 'IND', 'IOWA', 'MARY', 'MICH', 'MINN', 'NEB', 'NW', 'WISC'], dtype='object')

RICE
Index(['LT', 'MRSH', 'MTSU', 'UAB', 'UNT', 'USM', 'UTEP', 'UTSA', 'WKU'], dtype='object')
SCHEDULING ERROR: WKU

RUTG
Index(['IND', 'MARY', 'MICH', 'MINN', 'MSU', 'NW', 'OHST', 'PSU', 'WISC'], dtype='object')

SCAR
Index(['ARK', 'AUB', 'FLA', 'KENT', 'MIZZ', 'TAMU', 'TENN', 'UGA', 'VAND'], dtype='object')

SDSU
Index(['AF', 'FRES', 'HWI', 'NEV', 'SJSU', 'UNLV', 'UNM', 'USU', 'WYO'], dtype='object')

SJSU
Index(['AF', 'CSU', 'FRES', 'HWI', 'NEV', 'SDSU', 'UNLV', 'USU', 'WYO'], dtype='object')

SMU
Index(['CONN', 'ECU', 'HOU', 'MEM', 'NAVY', 'TEM', 'TULN', 'TULS', 'UCF'], dtype='object')

STAN
Index(['ASU', 'CAL', 'ORE', 'ORST', 'UCLA', 'USC', 'WASH', 'WSU', 'ZONA'], dtype='object')

TAMU
Index(['ARK', 'AUB', 'BAMA', 'KENT', 'LSU', 'MISS', 'MSST', 'SCAR', 'VAND'], dtype='object')

TCU
Index(['BAY', 'ISU', 'KAN', 'KSU', 'OKLA', 'OKST', 'TEX', 'TTU', 'WVU'], dtype='object')

TEM
Index(['CIN', 'CONN', 'ECU', 'MEM', 'NAVY', 'SMU', 'TULS', 'UCF', 'USF'], dtype='object')

TENN
Index(['ARK', 'BAMA', 'FLA', 'KENT', 'MIZZ', 'MSST', 'SCAR', 'UGA', 'VAND'], dtype='object')
SCHEDULING ERROR: VAND

TEX
Index(['BAY', 'ISU', 'KAN', 'KSU', 'OKLA', 'OKST', 'TCU', 'TTU', 'WVU'], dtype='object')

TOL
Index(['BALL', 'BUFF', 'CMU', 'EMU', 'KNTS', 'MIOH', 'NIU', 'OHIO', 'WMU'], dtype='object')

TROY
Index(['APP', 'ARST', 'CCAR', 'GAST', 'GSOU', 'TXST', 'ULL', 'ULM', 'USA'], dtype='object')

TTU
Index(['BAY', 'ISU', 'KAN', 'KSU', 'OKLA', 'OKST', 'TCU', 'TEX', 'WVU'], dtype='object')

TULN
Index(['CIN', 'CONN', 'ECU', 'HOU', 'MEM', 'NAVY', 'SMU', 'TULS', 'USF'], dtype='object')

TULS
Index(['CONN', 'HOU', 'MEM', 'NAVY', 'SMU', 'TEM', 'TULN', 'UCF', 'USF'], dtype='object')

TXST
Index(['APP', 'ARST', 'CCAR', 'GAST', 'GSOU', 'TROY', 'ULL', 'ULM', 'USA'], dtype='object')

UAB
Index(['CHAR', 'FAU', 'LT', 'ODU', 'RICE', 'UNT', 'USM', 'UTEP', 'UTSA'], dtype='object')

UCF
Index(['CIN', 'CONN', 'ECU', 'HOU', 'NAVY', 'SMU', 'TEM', 'TULS', 'USF'], dtype='object')
SCHEDULING ERROR: USF

UCLA
Index(['ASU', 'CAL', 'COL', 'ORE', 'STAN', 'USC', 'UTAH', 'WASH', 'ZONA'], dtype='object')

UGA
Index(['AUB', 'FLA', 'KENT', 'LSU', 'MIZZ', 'MSST', 'SCAR', 'TENN', 'VAND'], dtype='object')
SCHEDULING ERROR: MSST

ULL
Index(['APP', 'ARST', 'CCAR', 'GAST', 'GSOU', 'TROY', 'TXST', 'ULM', 'USA'], dtype='object')

ULM
Index(['APP', 'ARST', 'CCAR', 'GAST', 'GSOU', 'TROY', 'TXST', 'ULL', 'USA'], dtype='object')

UNC
Index(['CLEM', 'DUKE', 'FSU', 'GT', 'MIA', 'NCST', 'PITT', 'UVA', 'VT'], dtype='object')

UNLV
Index(['AF', 'BSU', 'FRES', 'HWI', 'NEV', 'SDSU', 'SJSU', 'UNM', 'USU'], dtype='object')

UNM
Index(['AF', 'BSU', 'CSU', 'FRES', 'HWI', 'SDSU', 'UNLV', 'USU', 'WYO'], dtype='object')
SCHEDULING ERROR: WYO

UNT
Index(['FIU', 'LT', 'MTSU', 'ODU', 'RICE', 'UAB', 'USM', 'UTEP', 'UTSA'], dtype='object')

USA
Index(['APP', 'ARST', 'CCAR', 'GAST', 'GSOU', 'TROY', 'TXST', 'ULL', 'ULM'], dtype='object')

USC
Index(['ASU', 'CAL', 'COL', 'ORST', 'STAN', 'UCLA', 'UTAH', 'WSU', 'ZONA'], dtype='object')

USF
Index(['CIN', 'CONN', 'ECU', 'HOU', 'MEM', 'TEM', 'TULN', 'TULS', 'UCF'], dtype='object')
SCHEDULING ERROR: UCF

USM
Index(['FIU', 'LT', 'MTSU', 'ODU', 'RICE', 'UAB', 'UNT', 'UTEP', 'UTSA'], dtype='object')

USU
Index(['AF', 'BSU', 'CSU', 'FRES', 'SDSU', 'SJSU', 'UNLV', 'UNM', 'WYO'], dtype='object')

UTAH
Index(['ASU', 'CAL', 'COL', 'ORE', 'ORST', 'UCLA', 'USC', 'WASH', 'ZONA'], dtype='object')

UTEP
Index(['CHAR', 'FIU', 'LT', 'RICE', 'UAB', 'UNT', 'USM', 'UTSA', 'WKU'], dtype='object')

UTSA
Index(['CHAR', 'FAU', 'LT', 'MRSH', 'RICE', 'UAB', 'UNT', 'USM', 'UTEP'], dtype='object')

UVA
Index(['DUKE', 'GT', 'LOU', 'MIA', 'NCST', 'PITT', 'UNC', 'VT', 'WAKE'], dtype='object')

VAND
Index(['BAMA', 'FLA', 'KENT', 'MISS', 'MIZZ', 'SCAR', 'TAMU', 'TENN', 'UGA'], dtype='object')
SCHEDULING ERROR: TENN

VT
Index(['BC', 'CUSE', 'DUKE', 'GT', 'LOU', 'MIA', 'PITT', 'UNC', 'UVA'], dtype='object')

WAKE
Index(['BC', 'CLEM', 'CUSE', 'DUKE', 'FSU', 'LOU', 'MIA', 'NCST', 'UVA'], dtype='object')

WASH
Index(['ASU', 'CAL', 'ORE', 'ORST', 'STAN', 'UCLA', 'UTAH', 'WSU', 'ZONA'], dtype='object')

WISC
Index(['ILL', 'IOWA', 'MINN', 'MSU', 'NEB', 'NW', 'PSU', 'PURD', 'RUTG'], dtype='object')

WKU
Index(['CHAR', 'FAU', 'FIU', 'LT', 'MRSH', 'MTSU', 'ODU', 'RICE', 'UTEP'], dtype='object')
SCHEDULING ERROR: RICE

WMU
Index(['AKR', 'BALL', 'BGSU', 'BUFF', 'CMU', 'EMU', 'NIU', 'OHIO', 'TOL'], dtype='object')

WSU
Index(['ASU', 'CAL', 'COL', 'ORE', 'ORST', 'STAN', 'USC', 'WASH', 'ZONA'], dtype='object')

WVU
Index(['BAY', 'ISU', 'KAN', 'KSU', 'OKLA', 'OKST', 'TCU', 'TEX', 'TTU'], dtype='object')

WYO
Index(['AF', 'BSU', 'CSU', 'HWI', 'NEV', 'SDSU', 'SJSU', 'UNM', 'USU'], dtype='object')
SCHEDULING ERROR: UNM

ZONA
Index(['ASU', 'COL', 'ORE', 'STAN', 'UCLA', 'USC', 'UTAH', 'WASH', 'WSU'], dtype='object')

In [9]:
weekly

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
AF,,,,USU,@UNLV,CSU,@SDSU,,NEV,SJSU,@UNM,,WYO,BSU,
AKR,,,,BALL,BGSU,,,WMU,@CMU,OHIO,KNTS,@MIOH,@BUFF,,EMU
APP,,,,GSOU,@TROY,@ULM,,@CCAR,,ARST,USA,,@ULL,TXST,@GAST
ARK,,,,@MIZZ,@TAMU,SCAR,,MISS,TENN,@MSST,@BAMA,,LSU,,@AUB
ARMY,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WMU,,,,EMU,,,OHIO,@AKR,@TOL,BALL,,CMU,@NIU,BUFF,@BGSU
WSU,,,,WASH,,@STAN,@ASU,ZONA,USC,ORST,,COL,CAL,@ORE,
WVU,,,,BAY,@ISU,@TTU,OKLA,,OKST,TCU,KSU,@TEX,,@KAN,
WYO,,,,NEV,@CSU,@HWI,@BSU,SJSU,,,,USU,@AF,,SDSU
ZONA,,,,,@UTAH,@COL,ORE,@WSU,,@ASU,@STAN,@USC,UCLA,,@WASH

In [10]:
weekly.to_csv("weeklySchedule2020.csv")